import React from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  TextField,
  DialogActions,
  Button,
} from '@mui/material';
import { userToAbsolute } from '../utils';

// Mostly generated by ChatGPT

function PrintDialog({ open, handleClose, handlePrint }) {
  const [formValues, setFormValues] = React.useState({
    x: '',
    y: '',
    width: '',
    height: '',
    scale: '',
  });

  const [errors, setErrors] = React.useState({
    x: false,
    y: false,
    width: false,
    height: false,
    scale: false,
  });


  const handleInputChange = (event) => {
    const { name, value } = event.target;
    setFormValues({
      ...formValues,
      [name]: value,
    });
  };

  const validateForm = () => {
    const newErrors = {
      x: isNaN(formValues.x),
      y: isNaN(formValues.y),
      width: isNaN(formValues.width),
      height: isNaN(formValues.height),
      scale: isNaN(formValues.scale),
    };
    setErrors(newErrors);
    return !Object.values(newErrors).some((error) => error);
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    if (validateForm()) {
        
      handlePrint(
        userToAbsolute(formValues.x),
        userToAbsolute(formValues.y),
        userToAbsolute(formValues.width),
        userToAbsolute(formValues.height),
        formValues.scale,
      )
      handleClose();
    }
  };

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      PaperProps={{
        component: 'form',
        onSubmit: handleSubmit,
      }}
    >
      <DialogTitle>Print Image Selection</DialogTitle>
      <DialogContent>
        <DialogContentText>
          Please enter the coordinates, dimensions, and scale for the image selection you
          want to print.
        </DialogContentText>
        <TextField
          required
          margin="dense"
          id="x"
          name="x"
          label="X Coordinate"
          type="text"
          value={formValues.x}
          onChange={handleInputChange}
          error={errors.x}
          helperText={errors.x ? 'Please enter a valid number' : ''}
        />
        <TextField
          required
          margin="dense"
          id="y"
          name="y"
          label="Y Coordinate"
          type="text"
          value={formValues.y}
          onChange={handleInputChange}
          error={errors.y}
          helperText={errors.y ? 'Please enter a valid number' : ''}
        />
        <TextField
          required
          margin="dense"
          id="width"
          name="width"
          label="Width"
          type="text"
          value={formValues.width}
          onChange={handleInputChange}
          error={errors.width}
          helperText={errors.width ? 'Please enter a valid number' : ''}
        />
        <TextField
          required
          margin="dense"
          id="height"
          name="height"
          label="Height"
          type="text"
          value={formValues.height}
          onChange={handleInputChange}
          error={errors.height}
          helperText={errors.height ? 'Please enter a valid number' : ''}
        />
        <TextField
          required
          margin="dense"
          id="scale"
          name="scale"
          label="Scale"
          type="text"
          value={formValues.scale}
          onChange={handleInputChange}
          error={errors.scale}
          helperText={errors.scale ? 'Please enter a valid number' : ''}
        />
        <DialogContentText>
          {/* Explanation of how the scale works */}
          The scale determines the size ratio of the printed image. For example, a scale of 2 will double the size of the image, whereas a scale of 0.5 will reduce it to half.
        </DialogContentText>
      </DialogContent>
      <DialogActions>
        <Button onClick={handleClose}>Cancel</Button>
        <Button type="submit">Print</Button>
      </DialogActions>
    </Dialog>
  );
}

export default PrintDialog;
