import React from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  TextField,
  DialogActions,
  Button,
} from '@mui/material';
import { userToAbsolute } from '../utils';

// Mostly generated by ChatGPT

function PrintDialog({ open, handleClose, handlePrint }) {
  const [formValues, setFormValues] = React.useState({
    tlX: '',
    tlY: '',
    brX: '',
    brY: '',
    scale: '',
  });

  const [errors, setErrors] = React.useState({
    tlX: false,
    tlY: false,
    brX: false,
    brY: false,
    scale: false,
  });


  const handleInputChange = (event) => {
    const { name, value } = event.target;
    setFormValues({
      ...formValues,
      [name]: value,
    });
  };

  const validateForm = () => {
    const newErrors = {
      x: isNaN(formValues.tlX),
      y: isNaN(formValues.tlY),
      width: isNaN(formValues.brX),
      height: isNaN(formValues.brY),
      scale: isNaN(formValues.scale),
    };
    setErrors(newErrors);
    return !Object.values(newErrors).some((error) => error);
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    if (validateForm()) {
      let aTlX = userToAbsolute(formValues.tlX);
      let aTlY = userToAbsolute(formValues.tlY);
      let aBrX = userToAbsolute(formValues.brX);
      let aBrY = userToAbsolute(formValues.brY);

      handlePrint(aTlX, aTlY, aBrX-aTlX, aBrY-aTlY, formValues.scale);
      handleClose();
    }
  };

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      PaperProps={{
        component: 'form',
        onSubmit: handleSubmit,
      }}
    >
      <DialogTitle>Print Image Selection</DialogTitle>
      <DialogContent>
        <DialogContentText>
          Please enter the coordinates, dimensions, and scale for the image selection you
          want to print.
        </DialogContentText>
        <TextField
          required
          margin="dense"
          id="tlX"
          name="tlX"
          label="X (Top-Left)"
          type="text"
          value={formValues.tlX}
          onChange={handleInputChange}
          error={errors.tlX}
          helperText={errors.tlX ? 'Please enter a valid number' : ''}
        />
        <TextField
          required
          margin="dense"
          id="tlY"
          name="tlY"
          label="Y (Top-Left)"
          type="text"
          value={formValues.tlY}
          onChange={handleInputChange}
          error={errors.tlY}
          helperText={errors.tlY ? 'Please enter a valid number' : ''}
        />
        <TextField
          required
          margin="dense"
          id="brX"
          name="brX"
          label="X (Bottom-Right)"
          type="text"
          value={formValues.brX}
          onChange={handleInputChange}
          error={errors.brX}
          helperText={errors.brX ? 'Please enter a valid number' : ''}
        />
        <TextField
          required
          margin="dense"
          id="brY"
          name="brY"
          label="Y (Bottom-Right)"
          type="text"
          value={formValues.brY}
          onChange={handleInputChange}
          error={errors.brY}
          helperText={errors.brY ? 'Please enter a valid number' : ''}
        />
        <TextField
          required
          margin="dense"
          id="scale"
          name="scale"
          label="Scale"
          type="text"
          value={formValues.scale}
          onChange={handleInputChange}
          error={errors.scale}
          helperText={errors.scale ? 'Please enter a valid number' : ''}
        />
        <DialogContentText>
          {/* Explanation of how the scale works */}
          The scale determines the size ratio of the printed image. For example, a scale of 2 will double the size of the image, whereas a scale of 0.5 will reduce it to half.
        </DialogContentText>
      </DialogContent>
      <DialogActions>
        <Button onClick={handleClose}>Cancel</Button>
        <Button type="submit">Print</Button>
      </DialogActions>
    </Dialog>
  );
}

export default PrintDialog;
